version: '3'

services:
        web:
                build: ./web
                ports:
                        - "5000:5000"
                environment: 
                        - AWS_ACCESS_KEY_ID=
                        - AWS_SECRET_ACCESS_KEY=
                        - AWS_DEFAULT_REGION=
                links:
                        - db
        db:
                build: ./db                

